### ISSUE TITLE
Is it possible to use on Arch Linux?

### ISSUE THREAD

**Issue by Eddieddg1** [gloss-click/cs2-buttplug#3]
Just as the title says.

**Comment by gloss-click** [comment]
Don't see why it wouldn't work if you already have CS running, there's nothing Windows-specific. You'd need to build it yourself though.

**Comment by Eddieddg1** [comment]
Ok, I wanted to know before wasting my time trying to set it up.

**Comment by gloss-click** [comment]
Lemme know if you run into any problems!

**Comment by Eddieddg1** [comment]
Will do, I havent begun trying to build it yet, still trying to get arch properly setup on my new pc.
